// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen';

export { client } from './client.gen';
export { AuthService, DocumentsService, ImagesService, NewsService, type Options, PersonImagesService, PersonsService, PositionsService, UsersService, UtilsService } from './sdk.gen';
export type * from './types.gen';

export const OpenAPI = {
	get BASE() {
		return client.getConfig().baseURL ?? ''
	},
	set BASE(value: string) {
		client.setConfig({ baseURL: value })
	}
};

export class ApiError extends Error {
	status?: number;
	body?: unknown;

	constructor(message?: string, status?: number, body?: unknown) {
		super(message);
		this.name = 'ApiError';
		this.status = status;
		this.body = body;
	}
}
