// This file is auto-generated by @hey-api/openapi-ts

export const BlockedIPInfoSchema = {
    properties: {
        ip: {
            type: 'string',
            title: 'Ip'
        },
        blocked_until: {
            type: 'number',
            title: 'Blocked Until'
        },
        remaining_seconds: {
            type: 'integer',
            title: 'Remaining Seconds'
        },
        failed_attempts_count: {
            type: 'integer',
            title: 'Failed Attempts Count'
        },
        first_attempt_time: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Attempt Time'
        },
        last_attempt_time: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Attempt Time'
        },
        block_reason: {
            type: 'string',
            title: 'Block Reason'
        },
        user_agent: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Agent'
        },
        attempted_emails: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Attempted Emails',
            default: []
        }
    },
    type: 'object',
    required: [
        'ip',
        'blocked_until',
        'remaining_seconds',
        'failed_attempts_count',
        'block_reason'
    ],
    title: 'BlockedIPInfo',
    description: 'Blocked IP address information.'
} as const;

export const BlockedIPsListSchema = {
    properties: {
        blocked_ips: {
            items: {
                $ref: '#/components/schemas/BlockedIPInfo'
            },
            type: 'array',
            title: 'Blocked Ips'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'blocked_ips',
        'count'
    ],
    title: 'BlockedIPsList',
    description: 'List of blocked IP addresses.'
} as const;

export const Body_auth_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_auth-login_access_token'
} as const;

export const Body_documents_create_documentSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        }
    },
    type: 'object',
    required: [
        'file'
    ],
    title: 'Body_documents-create_document'
} as const;

export const Body_images_upload_imageSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: [
        'file'
    ],
    title: 'Body_images-upload_image'
} as const;

export const Body_person_images_upload_person_imageSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: [
        'file'
    ],
    title: 'Body_person-images-upload_person_image'
} as const;

export const DocumentCategoriesPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/DocumentCategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'DocumentCategoriesPublic',
    description: 'Document category list with count.'
} as const;

export const DocumentCategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'DocumentCategoryCreate',
    description: 'Schema for creating document category.'
} as const;

export const DocumentCategoryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'created_at'
    ],
    title: 'DocumentCategoryPublic',
    description: 'Public document category schema for API responses.'
} as const;

export const DocumentCategoryUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'DocumentCategoryUpdate',
    description: 'Schema for updating document category (all fields optional).'
} as const;

export const DocumentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        file_name: {
            type: 'string',
            title: 'File Name'
        },
        file_path: {
            type: 'string',
            title: 'File Path'
        },
        file_size: {
            type: 'integer',
            title: 'File Size'
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        category: {
            anyOf: [
                {
                    $ref: '#/components/schemas/DocumentCategoryPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        owner: {
            anyOf: [
                {
                    $ref: '#/components/schemas/UserPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'file_name',
        'file_path',
        'file_size',
        'mime_type',
        'owner_id',
        'created_at',
        'updated_at'
    ],
    title: 'DocumentPublic',
    description: 'Public document schema for API responses.'
} as const;

export const DocumentUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        }
    },
    type: 'object',
    title: 'DocumentUpdate',
    description: 'Schema for updating document (all fields optional).'
} as const;

export const DocumentsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/DocumentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'DocumentsPublic',
    description: 'Document list with count.'
} as const;

export const EmailVerificationCodeSchema = {
    properties: {
        new_email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'New Email'
        },
        code: {
            type: 'string',
            maxLength: 4,
            minLength: 4,
            title: 'Code'
        }
    },
    type: 'object',
    required: [
        'new_email',
        'code'
    ],
    title: 'EmailVerificationCode',
    description: 'Schema for email verification with code.'
} as const;

export const EmailVerificationRequestSchema = {
    properties: {
        new_email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'New Email'
        }
    },
    type: 'object',
    required: [
        'new_email'
    ],
    title: 'EmailVerificationRequest',
    description: 'Schema for requesting email verification code.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: [
        'message'
    ],
    title: 'Message',
    description: 'Generic message for API responses.'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'token',
        'new_password'
    ],
    title: 'NewPassword',
    description: 'Schema for password reset.'
} as const;

export const NewsCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        content: {
            type: 'string',
            minLength: 1,
            title: 'Content'
        },
        is_published: {
            type: 'boolean',
            title: 'Is Published',
            default: false
        }
    },
    type: 'object',
    required: [
        'title',
        'content'
    ],
    title: 'NewsCreate',
    description: 'Schema for creating news.'
} as const;

export const NewsImageListSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/NewsImagePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'NewsImageList',
    description: 'News image list with count.'
} as const;

export const NewsImagePublicSchema = {
    properties: {
        file_name: {
            type: 'string',
            maxLength: 255,
            title: 'File Name'
        },
        file_path: {
            type: 'string',
            maxLength: 512,
            title: 'File Path'
        },
        file_size: {
            type: 'integer',
            title: 'File Size'
        },
        mime_type: {
            type: 'string',
            maxLength: 100,
            title: 'Mime Type'
        },
        order: {
            type: 'integer',
            title: 'Order',
            default: 0
        },
        is_main: {
            type: 'boolean',
            title: 'Is Main',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        news_id: {
            type: 'string',
            format: 'uuid',
            title: 'News Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'file_name',
        'file_path',
        'file_size',
        'mime_type',
        'id',
        'news_id',
        'created_at'
    ],
    title: 'NewsImagePublic',
    description: 'Public news image schema for API responses.'
} as const;

export const NewsPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        content: {
            type: 'string',
            minLength: 1,
            title: 'Content'
        },
        is_published: {
            type: 'boolean',
            title: 'Is Published',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        owner: {
            anyOf: [
                {
                    $ref: '#/components/schemas/UserPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        published_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        images: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/NewsImagePublic'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Images'
        }
    },
    type: 'object',
    required: [
        'title',
        'content',
        'id',
        'owner_id',
        'published_at',
        'created_at',
        'updated_at'
    ],
    title: 'NewsPublic',
    description: 'Public news schema for API responses.'
} as const;

export const NewsPublicListSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/NewsPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'NewsPublicList',
    description: 'News list with count.'
} as const;

export const NewsUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        content: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        is_published: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Published'
        },
        owner_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Id'
        }
    },
    type: 'object',
    title: 'NewsUpdate',
    description: 'Schema for updating news (all fields optional).'
} as const;

export const OrganizationCardCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        phones: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Phones'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        work_hours: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Work Hours'
        },
        vk_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vk Url'
        },
        telegram_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Url'
        },
        whatsapp_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Whatsapp Url'
        },
        max_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Url'
        },
        latitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latitude'
        },
        longitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Longitude'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'OrganizationCardCreate',
    description: 'Schema for creating organization card.'
} as const;

export const OrganizationCardPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        phones: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Phones'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        work_hours: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Work Hours'
        },
        vk_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vk Url'
        },
        telegram_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Url'
        },
        whatsapp_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Whatsapp Url'
        },
        max_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Url'
        },
        latitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latitude'
        },
        longitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Longitude'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'phones',
        'email',
        'address',
        'work_hours',
        'vk_url',
        'telegram_url',
        'whatsapp_url',
        'max_url',
        'latitude',
        'longitude',
        'created_at',
        'updated_at'
    ],
    title: 'OrganizationCardPublic',
    description: 'Public organization card schema.'
} as const;

export const OrganizationCardUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        phones: {
            anyOf: [
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phones'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        work_hours: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Work Hours'
        },
        vk_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vk Url'
        },
        telegram_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Url'
        },
        whatsapp_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Whatsapp Url'
        },
        max_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Url'
        },
        latitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latitude'
        },
        longitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Longitude'
        }
    },
    type: 'object',
    title: 'OrganizationCardUpdate',
    description: 'Schema for updating organization card (all fields optional).'
} as const;

export const PersonCreateSchema = {
    properties: {
        last_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Last Name'
        },
        first_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'First Name'
        },
        middle_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Middle Name'
        },
        phone: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Phone'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        description: {
            type: 'string',
            maxLength: 2000,
            title: 'Description',
            default: ''
        },
        position_id: {
            type: 'string',
            format: 'uuid',
            title: 'Position Id'
        }
    },
    type: 'object',
    required: [
        'last_name',
        'first_name',
        'middle_name',
        'phone',
        'email',
        'position_id'
    ],
    title: 'PersonCreate',
    description: 'Schema for creating person.'
} as const;

export const PersonImagePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        person_id: {
            type: 'string',
            format: 'uuid',
            title: 'Person Id'
        },
        file_name: {
            type: 'string',
            title: 'File Name'
        },
        file_path: {
            type: 'string',
            title: 'File Path'
        },
        file_size: {
            type: 'integer',
            title: 'File Size'
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'person_id',
        'file_name',
        'file_path',
        'file_size',
        'mime_type',
        'created_at'
    ],
    title: 'PersonImagePublic',
    description: 'Public person image schema for API responses.'
} as const;

export const PersonPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        middle_name: {
            type: 'string',
            title: 'Middle Name'
        },
        phone: {
            type: 'string',
            title: 'Phone'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        position: {
            $ref: '#/components/schemas/PositionPublic'
        },
        image: {
            anyOf: [
                {
                    $ref: '#/components/schemas/PersonImagePublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'last_name',
        'first_name',
        'middle_name',
        'phone',
        'email',
        'description',
        'position',
        'created_at',
        'updated_at'
    ],
    title: 'PersonPublic',
    description: 'Public person schema for API responses.'
} as const;

export const PersonUpdateSchema = {
    properties: {
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        middle_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Middle Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        position_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position Id'
        }
    },
    type: 'object',
    title: 'PersonUpdate',
    description: 'Schema for updating person (all fields optional).'
} as const;

export const PersonsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/PersonPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'PersonsPublic',
    description: 'Person list with count.'
} as const;

export const PositionCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'PositionCreate',
    description: 'Schema for creating position.'
} as const;

export const PositionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'created_at'
    ],
    title: 'PositionPublic',
    description: 'Public position schema for API responses.'
} as const;

export const PositionUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'PositionUpdate',
    description: 'Schema for updating position (all fields optional).'
} as const;

export const PositionsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/PositionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'PositionsPublic',
    description: 'Position list with count.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: [
        'access_token'
    ],
    title: 'Token',
    description: 'Access token schema.'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'current_password',
        'new_password'
    ],
    title: 'UpdatePassword',
    description: 'Schema for password update.'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Full Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        }
    },
    type: 'object',
    required: [
        'email',
        'password',
        'full_name'
    ],
    title: 'UserCreate',
    description: 'Schema for creating user via API.'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            type: 'string',
            maxLength: 255,
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        is_first_superuser: {
            type: 'boolean',
            title: 'Is First Superuser',
            default: false
        }
    },
    type: 'object',
    required: [
        'email',
        'full_name',
        'id'
    ],
    title: 'UserPublic',
    description: 'Public user schema for API responses.'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: 'Schema for updating user (all fields optional).\nis_superuser can only be changed by superuser.'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe',
    description: 'Schema for updating own user profile.'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'UsersPublic',
    description: 'User list with count.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
