// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * BlockedIPInfo
 *
 * Blocked IP address information.
 */
export type BlockedIpInfo = {
    /**
     * Ip
     */
    ip: string;
    /**
     * Blocked Until
     */
    blocked_until: number;
    /**
     * Remaining Seconds
     */
    remaining_seconds: number;
    /**
     * Failed Attempts Count
     */
    failed_attempts_count: number;
    /**
     * First Attempt Time
     */
    first_attempt_time?: number | null;
    /**
     * Last Attempt Time
     */
    last_attempt_time?: number | null;
    /**
     * Block Reason
     */
    block_reason: string;
    /**
     * User Agent
     */
    user_agent?: string | null;
    /**
     * Attempted Emails
     */
    attempted_emails?: Array<string>;
};

/**
 * BlockedIPsList
 *
 * List of blocked IP addresses.
 */
export type BlockedIpsList = {
    /**
     * Blocked Ips
     */
    blocked_ips: Array<BlockedIpInfo>;
    /**
     * Count
     */
    count: number;
};

/**
 * Body_auth-login_access_token
 */
export type BodyAuthLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_documents-create_document
 */
export type BodyDocumentsCreateDocument = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Category Id
     */
    category_id?: string | null;
};

/**
 * Body_images-upload_image
 */
export type BodyImagesUploadImage = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * DocumentCategoriesPublic
 *
 * Document category list with count.
 */
export type DocumentCategoriesPublic = {
    /**
     * Data
     */
    data: Array<DocumentCategoryPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * DocumentCategoryCreate
 *
 * Schema for creating document category.
 */
export type DocumentCategoryCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * DocumentCategoryPublic
 *
 * Public document category schema for API responses.
 */
export type DocumentCategoryPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * DocumentCategoryUpdate
 *
 * Schema for updating document category (all fields optional).
 */
export type DocumentCategoryUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * DocumentPublic
 *
 * Public document schema for API responses.
 */
export type DocumentPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * File Name
     */
    file_name: string;
    /**
     * File Path
     */
    file_path: string;
    /**
     * File Size
     */
    file_size: number;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Category Id
     */
    category_id?: string | null;
    category?: DocumentCategoryPublic | null;
    /**
     * Owner Id
     */
    owner_id: string;
    owner?: UserPublic | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DocumentUpdate
 *
 * Schema for updating document (all fields optional).
 */
export type DocumentUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Category Id
     */
    category_id?: string | null;
};

/**
 * DocumentsPublic
 *
 * Document list with count.
 */
export type DocumentsPublic = {
    /**
     * Data
     */
    data: Array<DocumentPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * EmailVerificationCode
 *
 * Schema for email verification with code.
 */
export type EmailVerificationCode = {
    /**
     * New Email
     */
    new_email: string;
    /**
     * Code
     */
    code: string;
};

/**
 * EmailVerificationRequest
 *
 * Schema for requesting email verification code.
 */
export type EmailVerificationRequest = {
    /**
     * New Email
     */
    new_email: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 *
 * Generic message for API responses.
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 *
 * Schema for password reset.
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * NewsCreate
 *
 * Schema for creating news.
 */
export type NewsCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Is Published
     */
    is_published?: boolean;
};

/**
 * NewsImageList
 *
 * News image list with count.
 */
export type NewsImageList = {
    /**
     * Data
     */
    data: Array<NewsImagePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * NewsImagePublic
 *
 * Public news image schema for API responses.
 */
export type NewsImagePublic = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * File Path
     */
    file_path: string;
    /**
     * File Size
     */
    file_size: number;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Order
     */
    order?: number;
    /**
     * Is Main
     */
    is_main?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * News Id
     */
    news_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * NewsPublic
 *
 * Public news schema for API responses.
 */
export type NewsPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Is Published
     */
    is_published?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Published At
     */
    published_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Images
     */
    images?: Array<NewsImagePublic> | null;
};

/**
 * NewsPublicList
 *
 * News list with count.
 */
export type NewsPublicList = {
    /**
     * Data
     */
    data: Array<NewsPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * NewsUpdate
 *
 * Schema for updating news (all fields optional).
 */
export type NewsUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Is Published
     */
    is_published?: boolean | null;
};

/**
 * Token
 *
 * Access token schema.
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 *
 * Schema for password update.
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 *
 * Schema for creating user via API.
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * UserPublic
 *
 * Public user schema for API responses.
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
};

/**
 * UserUpdate
 *
 * Schema for updating user (all fields optional).
 * is_superuser can only be changed by superuser.
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
};

/**
 * UserUpdateMe
 *
 * Schema for updating own user profile.
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 *
 * User list with count.
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type NewsReadPublicNewsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/news/public';
};

export type NewsReadPublicNewsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewsReadPublicNewsError = NewsReadPublicNewsErrors[keyof NewsReadPublicNewsErrors];

export type NewsReadPublicNewsResponses = {
    /**
     * Successful Response
     */
    200: NewsPublicList;
};

export type NewsReadPublicNewsResponse = NewsReadPublicNewsResponses[keyof NewsReadPublicNewsResponses];

export type AuthLoginAccessTokenData = {
    body: BodyAuthLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/auth/access-token';
};

export type AuthLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginAccessTokenError = AuthLoginAccessTokenErrors[keyof AuthLoginAccessTokenErrors];

export type AuthLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type AuthLoginAccessTokenResponse = AuthLoginAccessTokenResponses[keyof AuthLoginAccessTokenResponses];

export type AuthRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/auth/password-recovery/{email}';
};

export type AuthRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthRecoverPasswordError = AuthRecoverPasswordErrors[keyof AuthRecoverPasswordErrors];

export type AuthRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type AuthRecoverPasswordResponse = AuthRecoverPasswordResponses[keyof AuthRecoverPasswordResponses];

export type AuthResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/auth/reset-password/';
};

export type AuthResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthResetPasswordError = AuthResetPasswordErrors[keyof AuthResetPasswordErrors];

export type AuthResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type AuthResetPasswordResponse = AuthResetPasswordResponses[keyof AuthResetPasswordResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersRequestEmailVerificationCodeData = {
    body: EmailVerificationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/email/request-code';
};

export type UsersRequestEmailVerificationCodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRequestEmailVerificationCodeError = UsersRequestEmailVerificationCodeErrors[keyof UsersRequestEmailVerificationCodeErrors];

export type UsersRequestEmailVerificationCodeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersRequestEmailVerificationCodeResponse = UsersRequestEmailVerificationCodeResponses[keyof UsersRequestEmailVerificationCodeResponses];

export type UsersVerifyAndUpdateEmailData = {
    body: EmailVerificationCode;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/email/verify';
};

export type UsersVerifyAndUpdateEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersVerifyAndUpdateEmailError = UsersVerifyAndUpdateEmailErrors[keyof UsersVerifyAndUpdateEmailErrors];

export type UsersVerifyAndUpdateEmailResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersVerifyAndUpdateEmailResponse = UsersVerifyAndUpdateEmailResponses[keyof UsersVerifyAndUpdateEmailResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type UtilsGetBlockedIpsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/blocked-ips/';
};

export type UtilsGetBlockedIpsResponses = {
    /**
     * Successful Response
     */
    200: BlockedIpsList;
};

export type UtilsGetBlockedIpsResponse = UtilsGetBlockedIpsResponses[keyof UtilsGetBlockedIpsResponses];

export type UtilsUnblockIpData = {
    body?: never;
    path: {
        /**
         * Ip Address
         */
        ip_address: string;
    };
    query?: never;
    url: '/api/v1/utils/unblock-ip/{ip_address}';
};

export type UtilsUnblockIpErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UtilsUnblockIpError = UtilsUnblockIpErrors[keyof UtilsUnblockIpErrors];

export type UtilsUnblockIpResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UtilsUnblockIpResponse = UtilsUnblockIpResponses[keyof UtilsUnblockIpResponses];

export type NewsReadNewsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/news/';
};

export type NewsReadNewsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewsReadNewsError = NewsReadNewsErrors[keyof NewsReadNewsErrors];

export type NewsReadNewsResponses = {
    /**
     * Successful Response
     */
    200: NewsPublicList;
};

export type NewsReadNewsResponse = NewsReadNewsResponses[keyof NewsReadNewsResponses];

export type NewsCreateNewsData = {
    body: NewsCreate;
    path?: never;
    query?: never;
    url: '/api/v1/news/';
};

export type NewsCreateNewsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewsCreateNewsError = NewsCreateNewsErrors[keyof NewsCreateNewsErrors];

export type NewsCreateNewsResponses = {
    /**
     * Successful Response
     */
    200: NewsPublic;
};

export type NewsCreateNewsResponse = NewsCreateNewsResponses[keyof NewsCreateNewsResponses];

export type NewsDeleteNewsData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/news/{id}';
};

export type NewsDeleteNewsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewsDeleteNewsError = NewsDeleteNewsErrors[keyof NewsDeleteNewsErrors];

export type NewsDeleteNewsResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type NewsDeleteNewsResponse = NewsDeleteNewsResponses[keyof NewsDeleteNewsResponses];

export type NewsReadNewsItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/news/{id}';
};

export type NewsReadNewsItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewsReadNewsItemError = NewsReadNewsItemErrors[keyof NewsReadNewsItemErrors];

export type NewsReadNewsItemResponses = {
    /**
     * Successful Response
     */
    200: NewsPublic;
};

export type NewsReadNewsItemResponse = NewsReadNewsItemResponses[keyof NewsReadNewsItemResponses];

export type NewsUpdateNewsData = {
    body: NewsUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/news/{id}';
};

export type NewsUpdateNewsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewsUpdateNewsError = NewsUpdateNewsErrors[keyof NewsUpdateNewsErrors];

export type NewsUpdateNewsResponses = {
    /**
     * Successful Response
     */
    200: NewsPublic;
};

export type NewsUpdateNewsResponse = NewsUpdateNewsResponses[keyof NewsUpdateNewsResponses];

export type ImagesGetImagesData = {
    body?: never;
    path: {
        /**
         * News Id
         */
        news_id: string;
    };
    query?: never;
    url: '/api/v1/news/{news_id}/images/';
};

export type ImagesGetImagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImagesGetImagesError = ImagesGetImagesErrors[keyof ImagesGetImagesErrors];

export type ImagesGetImagesResponses = {
    /**
     * Successful Response
     */
    200: NewsImageList;
};

export type ImagesGetImagesResponse = ImagesGetImagesResponses[keyof ImagesGetImagesResponses];

export type ImagesUploadImageData = {
    body: BodyImagesUploadImage;
    path: {
        /**
         * News Id
         */
        news_id: string;
    };
    query?: never;
    url: '/api/v1/news/{news_id}/images/';
};

export type ImagesUploadImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImagesUploadImageError = ImagesUploadImageErrors[keyof ImagesUploadImageErrors];

export type ImagesUploadImageResponses = {
    /**
     * Successful Response
     */
    200: NewsImagePublic;
};

export type ImagesUploadImageResponse = ImagesUploadImageResponses[keyof ImagesUploadImageResponses];

export type ImagesDeleteImageData = {
    body?: never;
    path: {
        /**
         * News Id
         */
        news_id: string;
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/api/v1/news/{news_id}/images/{image_id}';
};

export type ImagesDeleteImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImagesDeleteImageError = ImagesDeleteImageErrors[keyof ImagesDeleteImageErrors];

export type ImagesDeleteImageResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ImagesDeleteImageResponse = ImagesDeleteImageResponses[keyof ImagesDeleteImageResponses];

export type ImagesReorderImageData = {
    body?: never;
    path: {
        /**
         * News Id
         */
        news_id: string;
        /**
         * Image Id
         */
        image_id: string;
    };
    query: {
        /**
         * New Order
         */
        new_order: number;
    };
    url: '/api/v1/news/{news_id}/images/{image_id}/reorder';
};

export type ImagesReorderImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImagesReorderImageError = ImagesReorderImageErrors[keyof ImagesReorderImageErrors];

export type ImagesReorderImageResponses = {
    /**
     * Successful Response
     */
    200: NewsImagePublic;
};

export type ImagesReorderImageResponse = ImagesReorderImageResponses[keyof ImagesReorderImageResponses];

export type ImagesSetMainImageData = {
    body?: never;
    path: {
        /**
         * News Id
         */
        news_id: string;
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/api/v1/news/{news_id}/images/{image_id}/set-main';
};

export type ImagesSetMainImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImagesSetMainImageError = ImagesSetMainImageErrors[keyof ImagesSetMainImageErrors];

export type ImagesSetMainImageResponses = {
    /**
     * Successful Response
     */
    200: NewsImagePublic;
};

export type ImagesSetMainImageResponse = ImagesSetMainImageResponses[keyof ImagesSetMainImageResponses];

export type ImagesGetImageFileData = {
    body?: never;
    path: {
        /**
         * News Id
         */
        news_id: string;
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/api/v1/news/{news_id}/images/{image_id}/file';
};

export type ImagesGetImageFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImagesGetImageFileError = ImagesGetImageFileErrors[keyof ImagesGetImageFileErrors];

export type ImagesGetImageFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DocumentsReadCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/documents/categories';
};

export type DocumentsReadCategoriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsReadCategoriesError = DocumentsReadCategoriesErrors[keyof DocumentsReadCategoriesErrors];

export type DocumentsReadCategoriesResponses = {
    /**
     * Successful Response
     */
    200: DocumentCategoriesPublic;
};

export type DocumentsReadCategoriesResponse = DocumentsReadCategoriesResponses[keyof DocumentsReadCategoriesResponses];

export type DocumentsCreateCategoryData = {
    body: DocumentCategoryCreate;
    path?: never;
    query?: never;
    url: '/api/v1/documents/categories';
};

export type DocumentsCreateCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsCreateCategoryError = DocumentsCreateCategoryErrors[keyof DocumentsCreateCategoryErrors];

export type DocumentsCreateCategoryResponses = {
    /**
     * Successful Response
     */
    200: DocumentCategoryPublic;
};

export type DocumentsCreateCategoryResponse = DocumentsCreateCategoryResponses[keyof DocumentsCreateCategoryResponses];

export type DocumentsDeleteCategoryData = {
    body?: never;
    path: {
        /**
         * Category Id
         */
        category_id: string;
    };
    query?: never;
    url: '/api/v1/documents/categories/{category_id}';
};

export type DocumentsDeleteCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsDeleteCategoryError = DocumentsDeleteCategoryErrors[keyof DocumentsDeleteCategoryErrors];

export type DocumentsDeleteCategoryResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DocumentsDeleteCategoryResponse = DocumentsDeleteCategoryResponses[keyof DocumentsDeleteCategoryResponses];

export type DocumentsUpdateCategoryData = {
    body: DocumentCategoryUpdate;
    path: {
        /**
         * Category Id
         */
        category_id: string;
    };
    query?: never;
    url: '/api/v1/documents/categories/{category_id}';
};

export type DocumentsUpdateCategoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsUpdateCategoryError = DocumentsUpdateCategoryErrors[keyof DocumentsUpdateCategoryErrors];

export type DocumentsUpdateCategoryResponses = {
    /**
     * Successful Response
     */
    200: DocumentCategoryPublic;
};

export type DocumentsUpdateCategoryResponse = DocumentsUpdateCategoryResponses[keyof DocumentsUpdateCategoryResponses];

export type DocumentsReadDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category Id
         */
        category_id?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/documents/';
};

export type DocumentsReadDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsReadDocumentsError = DocumentsReadDocumentsErrors[keyof DocumentsReadDocumentsErrors];

export type DocumentsReadDocumentsResponses = {
    /**
     * Successful Response
     */
    200: DocumentsPublic;
};

export type DocumentsReadDocumentsResponse = DocumentsReadDocumentsResponses[keyof DocumentsReadDocumentsResponses];

export type DocumentsCreateDocumentData = {
    body: BodyDocumentsCreateDocument;
    path?: never;
    query?: never;
    url: '/api/v1/documents/';
};

export type DocumentsCreateDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsCreateDocumentError = DocumentsCreateDocumentErrors[keyof DocumentsCreateDocumentErrors];

export type DocumentsCreateDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentPublic;
};

export type DocumentsCreateDocumentResponse = DocumentsCreateDocumentResponses[keyof DocumentsCreateDocumentResponses];

export type DocumentsDeleteDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}';
};

export type DocumentsDeleteDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsDeleteDocumentError = DocumentsDeleteDocumentErrors[keyof DocumentsDeleteDocumentErrors];

export type DocumentsDeleteDocumentResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DocumentsDeleteDocumentResponse = DocumentsDeleteDocumentResponses[keyof DocumentsDeleteDocumentResponses];

export type DocumentsReadDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}';
};

export type DocumentsReadDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsReadDocumentError = DocumentsReadDocumentErrors[keyof DocumentsReadDocumentErrors];

export type DocumentsReadDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentPublic;
};

export type DocumentsReadDocumentResponse = DocumentsReadDocumentResponses[keyof DocumentsReadDocumentResponses];

export type DocumentsUpdateDocumentData = {
    body: DocumentUpdate;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}';
};

export type DocumentsUpdateDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsUpdateDocumentError = DocumentsUpdateDocumentErrors[keyof DocumentsUpdateDocumentErrors];

export type DocumentsUpdateDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentPublic;
};

export type DocumentsUpdateDocumentResponse = DocumentsUpdateDocumentResponses[keyof DocumentsUpdateDocumentResponses];

export type DocumentsGetDocumentFileData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}/file';
};

export type DocumentsGetDocumentFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsGetDocumentFileError = DocumentsGetDocumentFileErrors[keyof DocumentsGetDocumentFileErrors];

export type DocumentsGetDocumentFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
