// This file is auto-generated by @hey-api/openapi-ts

/**
 * Blocked IP address information.
 */
export type BlockedIPInfo = {
    ip: string;
    blocked_until: number;
    remaining_seconds: number;
    failed_attempts_count: number;
    first_attempt_time?: (number | null);
    last_attempt_time?: (number | null);
    block_reason: string;
    user_agent?: (string | null);
    attempted_emails?: Array<(string)>;
};

/**
 * List of blocked IP addresses.
 */
export type BlockedIPsList = {
    blocked_ips: Array<BlockedIPInfo>;
    count: number;
};

export type Body_auth_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_documents_create_document = {
    file: (Blob | File);
    name?: (string | null);
    category_id?: (string | null);
    category_name?: (string | null);
};

export type Body_images_upload_image = {
    file: (Blob | File);
};

/**
 * Document category list with count.
 */
export type DocumentCategoriesPublic = {
    data: Array<DocumentCategoryPublic>;
    count: number;
};

/**
 * Schema for creating document category.
 */
export type DocumentCategoryCreate = {
    name: string;
};

/**
 * Public document category schema for API responses.
 */
export type DocumentCategoryPublic = {
    id: string;
    name: string;
    created_at: string;
};

/**
 * Public document schema for API responses.
 */
export type DocumentPublic = {
    id: string;
    name: string;
    file_name: string;
    file_path: string;
    file_size: number;
    mime_type: string;
    category_id?: (string | null);
    category?: (DocumentCategoryPublic | null);
    owner_id: string;
    owner?: (UserPublic | null);
    created_at: string;
    updated_at: string;
};

/**
 * Document list with count.
 */
export type DocumentsPublic = {
    data: Array<DocumentPublic>;
    count: number;
};

/**
 * Schema for updating document (all fields optional).
 */
export type DocumentUpdate = {
    name?: (string | null);
    category_id?: (string | null);
};

/**
 * Schema for email verification with code.
 */
export type EmailVerificationCode = {
    new_email: string;
    code: string;
};

/**
 * Schema for requesting email verification code.
 */
export type EmailVerificationRequest = {
    new_email: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Generic message for API responses.
 */
export type Message = {
    message: string;
};

/**
 * Schema for password reset.
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Schema for creating news.
 */
export type NewsCreate = {
    title: string;
    content: string;
    is_published?: boolean;
};

/**
 * News image list with count.
 */
export type NewsImageList = {
    data: Array<NewsImagePublic>;
    count: number;
};

/**
 * Public news image schema for API responses.
 */
export type NewsImagePublic = {
    file_name: string;
    file_path: string;
    file_size: number;
    mime_type: string;
    order?: number;
    is_main?: boolean;
    id: string;
    news_id: string;
    created_at: string;
};

/**
 * Public news schema for API responses.
 */
export type NewsPublic = {
    title: string;
    content: string;
    is_published?: boolean;
    id: string;
    owner_id: string;
    published_at: (string | null);
    created_at: string;
    updated_at: string;
    images?: (Array<NewsImagePublic> | null);
};

/**
 * News list with count.
 */
export type NewsPublicList = {
    data: Array<NewsPublic>;
    count: number;
};

/**
 * Schema for updating news (all fields optional).
 */
export type NewsUpdate = {
    title?: (string | null);
    content?: (string | null);
    is_published?: (boolean | null);
};

/**
 * Access token schema.
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Schema for password update.
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Schema for creating user via API.
 */
export type UserCreate = {
    email: string;
    password: string;
    full_name?: (string | null);
    is_active?: boolean;
};

/**
 * Public user schema for API responses.
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

/**
 * User list with count.
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Schema for updating user (all fields optional).
 * is_superuser can only be changed by superuser.
 */
export type UserUpdate = {
    email?: (string | null);
    password?: (string | null);
    full_name?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
};

/**
 * Schema for updating own user profile.
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AuthLoginAccessTokenData = {
    formData: Body_auth_login_access_token;
};

export type AuthLoginAccessTokenResponse = (Token);

export type AuthRecoverPasswordData = {
    email: string;
};

export type AuthRecoverPasswordResponse = (Message);

export type AuthResetPasswordData = {
    requestBody: NewPassword;
};

export type AuthResetPasswordResponse = (Message);

export type DocumentsReadCategoriesData = {
    limit?: number;
    skip?: number;
};

export type DocumentsReadCategoriesResponse = (DocumentCategoriesPublic);

export type DocumentsCreateCategoryData = {
    requestBody: DocumentCategoryCreate;
};

export type DocumentsCreateCategoryResponse = (DocumentCategoryPublic);

export type DocumentsDeleteCategoryData = {
    categoryId: string;
};

export type DocumentsDeleteCategoryResponse = (Message);

export type DocumentsReadDocumentsData = {
    categoryId?: (string | null);
    limit?: number;
    skip?: number;
};

export type DocumentsReadDocumentsResponse = (DocumentsPublic);

export type DocumentsCreateDocumentData = {
    formData: Body_documents_create_document;
};

export type DocumentsCreateDocumentResponse = (DocumentPublic);

export type DocumentsReadDocumentData = {
    documentId: string;
};

export type DocumentsReadDocumentResponse = (DocumentPublic);

export type DocumentsUpdateDocumentData = {
    documentId: string;
    requestBody: DocumentUpdate;
};

export type DocumentsUpdateDocumentResponse = (DocumentPublic);

export type DocumentsDeleteDocumentData = {
    documentId: string;
};

export type DocumentsDeleteDocumentResponse = (Message);

export type DocumentsGetDocumentFileData = {
    documentId: string;
};

export type DocumentsGetDocumentFileResponse = (unknown);

export type ImagesUploadImageData = {
    formData: Body_images_upload_image;
    newsId: string;
};

export type ImagesUploadImageResponse = (NewsImagePublic);

export type ImagesGetImagesData = {
    newsId: string;
};

export type ImagesGetImagesResponse = (NewsImageList);

export type ImagesDeleteImageData = {
    imageId: string;
    newsId: string;
};

export type ImagesDeleteImageResponse = (Message);

export type ImagesReorderImageData = {
    imageId: string;
    newOrder: number;
    newsId: string;
};

export type ImagesReorderImageResponse = (NewsImagePublic);

export type ImagesSetMainImageData = {
    imageId: string;
    newsId: string;
};

export type ImagesSetMainImageResponse = (NewsImagePublic);

export type ImagesGetImageFileData = {
    imageId: string;
    newsId: string;
};

export type ImagesGetImageFileResponse = (unknown);

export type NewsReadPublicNewsData = {
    limit?: number;
    skip?: number;
};

export type NewsReadPublicNewsResponse = (NewsPublicList);

export type NewsReadNewsData = {
    limit?: number;
    skip?: number;
};

export type NewsReadNewsResponse = (NewsPublicList);

export type NewsCreateNewsData = {
    requestBody: NewsCreate;
};

export type NewsCreateNewsResponse = (NewsPublic);

export type NewsReadNewsItemData = {
    id: string;
};

export type NewsReadNewsItemResponse = (NewsPublic);

export type NewsUpdateNewsData = {
    id: string;
    requestBody: NewsUpdate;
};

export type NewsUpdateNewsResponse = (NewsPublic);

export type NewsDeleteNewsData = {
    id: string;
};

export type NewsDeleteNewsResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersRequestEmailVerificationCodeData = {
    requestBody: EmailVerificationRequest;
};

export type UsersRequestEmailVerificationCodeResponse = (Message);

export type UsersVerifyAndUpdateEmailData = {
    requestBody: EmailVerificationCode;
};

export type UsersVerifyAndUpdateEmailResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsGetBlockedIpsResponse = (BlockedIPsList);

export type UtilsUnblockIpData = {
    ipAddress: string;
};

export type UtilsUnblockIpResponse = (Message);