"""Error codes for the application."""


class ErrorCode:
    """Error codes enum."""

    # Positions
    POSITION_EXISTS = "POSITION_EXISTS"
    POSITION_NOT_FOUND = "POSITION_NOT_FOUND"
    POSITION_DEFAULT_PROTECTED = "POSITION_DEFAULT_PROTECTED"

    # Persons
    PERSON_EXISTS = "PERSON_EXISTS"
    PERSON_NOT_FOUND = "PERSON_NOT_FOUND"
    PERSON_PHONE_EXISTS = "PERSON_PHONE_EXISTS"
    PERSON_EMAIL_EXISTS = "PERSON_EMAIL_EXISTS"

    # Person Images
    PERSON_IMAGE_NOT_FOUND = "PERSON_IMAGE_NOT_FOUND"

    # News
    NEWS_NOT_FOUND = "NEWS_NOT_FOUND"
    NEWS_FORBIDDEN = "NEWS_FORBIDDEN"
    NEWS_OWNER_NOT_FOUND = "NEWS_OWNER_NOT_FOUND"
    NEWS_OWNER_CHANGE_FORBIDDEN = "NEWS_OWNER_CHANGE_FORBIDDEN"

    # News Images
    NEWS_IMAGE_NOT_FOUND = "NEWS_IMAGE_NOT_FOUND"
    NEWS_IMAGE_INVALID_ORDER = "NEWS_IMAGE_INVALID_ORDER"

    # Documents
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    DOCUMENT_FILE_NOT_FOUND = "DOCUMENT_FILE_NOT_FOUND"
    DOCUMENT_FORBIDDEN = "DOCUMENT_FORBIDDEN"

    # Document Categories
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
    CATEGORY_EXISTS = "CATEGORY_EXISTS"
    CATEGORY_FORBIDDEN = "CATEGORY_FORBIDDEN"
    CATEGORY_INVALID_ID = "CATEGORY_INVALID_ID"

    # Organization Card
    ORG_CARD_NOT_FOUND = "ORG_CARD_NOT_FOUND"
    ORG_CARD_EXISTS = "ORG_CARD_EXISTS"

    # Auth
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_INACTIVE_USER = "AUTH_INACTIVE_USER"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"

    # Users
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_EMAIL_EXISTS = "USER_EMAIL_EXISTS"
    USER_NAME_EXISTS = "USER_NAME_EXISTS"
    USER_SUPERUSER_REQUIRED = "USER_SUPERUSER_REQUIRED"
    USER_EMAIL_CHANGE_FORBIDDEN = "USER_EMAIL_CHANGE_FORBIDDEN"
    USER_EMAIL_SAME = "USER_EMAIL_SAME"
    USER_EMAIL_NOT_SET = "USER_EMAIL_NOT_SET"
    USER_VERIFICATION_INVALID = "USER_VERIFICATION_INVALID"
    USER_PASSWORD_INCORRECT = "USER_PASSWORD_INCORRECT"
    USER_PASSWORD_SAME = "USER_PASSWORD_SAME"
    USER_DELETE_FIRST_SUPERUSER = "USER_DELETE_FIRST_SUPERUSER"
    USER_DELETE_GUARDIAN = "USER_DELETE_GUARDIAN"
    USER_GUARDIAN_NOT_FOUND = "USER_GUARDIAN_NOT_FOUND"
    USER_INSUFFICIENT_PRIVILEGES = "USER_INSUFFICIENT_PRIVILEGES"
    USER_SUPERUSER_SELF_DEMOTE = "USER_SUPERUSER_SELF_DEMOTE"
    USER_DELETE_SELF_FORBIDDEN = "USER_DELETE_SELF_FORBIDDEN"

    # Utils
    IP_BLOCKING_NOT_AVAILABLE = "IP_BLOCKING_NOT_AVAILABLE"
