/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsRouteImport } from './routes/news'
import { Route as FederationRouteImport } from './routes/federation'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRulesRouteImport } from './routes/docs/rules'
import { Route as DocsOrganizationalRouteImport } from './routes/docs/organizational'
import { Route as DocsLegalRouteImport } from './routes/docs/legal'
import { Route as DocsFinancialRouteImport } from './routes/docs/financial'
import { Route as DocsEducationRouteImport } from './routes/docs/education'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRecoverPasswordRouteImport } from './routes/auth/recover-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as LayoutUsersRouteImport } from './routes/_layout/users'
import { Route as LayoutManageNewsRouteImport } from './routes/_layout/manage-news'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'

const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const FederationRoute = FederationRouteImport.update({
  id: '/federation',
  path: '/federation',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRulesRoute = DocsRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => DocsRoute,
} as any)
const DocsOrganizationalRoute = DocsOrganizationalRouteImport.update({
  id: '/organizational',
  path: '/organizational',
  getParentRoute: () => DocsRoute,
} as any)
const DocsLegalRoute = DocsLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFinancialRoute = DocsFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => DocsRoute,
} as any)
const DocsEducationRoute = DocsEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => DocsRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoverPasswordRoute = AuthRecoverPasswordRouteImport.update({
  id: '/auth/recover-password',
  path: '/auth/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutManageNewsRoute = LayoutManageNewsRouteImport.update({
  id: '/manage-news',
  path: '/manage-news',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/docs': typeof DocsRouteWithChildren
  '/federation': typeof FederationRoute
  '/news': typeof NewsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/manage-news': typeof LayoutManageNewsRoute
  '/users': typeof LayoutUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/docs/education': typeof DocsEducationRoute
  '/docs/financial': typeof DocsFinancialRoute
  '/docs/legal': typeof DocsLegalRoute
  '/docs/organizational': typeof DocsOrganizationalRoute
  '/docs/rules': typeof DocsRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/docs': typeof DocsRouteWithChildren
  '/federation': typeof FederationRoute
  '/news': typeof NewsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/manage-news': typeof LayoutManageNewsRoute
  '/users': typeof LayoutUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/docs/education': typeof DocsEducationRoute
  '/docs/financial': typeof DocsFinancialRoute
  '/docs/legal': typeof DocsLegalRoute
  '/docs/organizational': typeof DocsOrganizationalRoute
  '/docs/rules': typeof DocsRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/docs': typeof DocsRouteWithChildren
  '/federation': typeof FederationRoute
  '/news': typeof NewsRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/manage-news': typeof LayoutManageNewsRoute
  '/_layout/users': typeof LayoutUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/docs/education': typeof DocsEducationRoute
  '/docs/financial': typeof DocsFinancialRoute
  '/docs/legal': typeof DocsLegalRoute
  '/docs/organizational': typeof DocsOrganizationalRoute
  '/docs/rules': typeof DocsRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contacts'
    | '/docs'
    | '/federation'
    | '/news'
    | '/dashboard'
    | '/manage-news'
    | '/users'
    | '/auth/login'
    | '/auth/recover-password'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/docs/education'
    | '/docs/financial'
    | '/docs/legal'
    | '/docs/organizational'
    | '/docs/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contacts'
    | '/docs'
    | '/federation'
    | '/news'
    | '/dashboard'
    | '/manage-news'
    | '/users'
    | '/auth/login'
    | '/auth/recover-password'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/docs/education'
    | '/docs/financial'
    | '/docs/legal'
    | '/docs/organizational'
    | '/docs/rules'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/about'
    | '/contacts'
    | '/docs'
    | '/federation'
    | '/news'
    | '/_layout/dashboard'
    | '/_layout/manage-news'
    | '/_layout/users'
    | '/auth/login'
    | '/auth/recover-password'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/docs/education'
    | '/docs/financial'
    | '/docs/legal'
    | '/docs/organizational'
    | '/docs/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactsRoute: typeof ContactsRoute
  DocsRoute: typeof DocsRouteWithChildren
  FederationRoute: typeof FederationRoute
  NewsRoute: typeof NewsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoverPasswordRoute: typeof AuthRecoverPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/federation': {
      id: '/federation'
      path: '/federation'
      fullPath: '/federation'
      preLoaderRoute: typeof FederationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/rules': {
      id: '/docs/rules'
      path: '/rules'
      fullPath: '/docs/rules'
      preLoaderRoute: typeof DocsRulesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/organizational': {
      id: '/docs/organizational'
      path: '/organizational'
      fullPath: '/docs/organizational'
      preLoaderRoute: typeof DocsOrganizationalRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/legal': {
      id: '/docs/legal'
      path: '/legal'
      fullPath: '/docs/legal'
      preLoaderRoute: typeof DocsLegalRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/financial': {
      id: '/docs/financial'
      path: '/financial'
      fullPath: '/docs/financial'
      preLoaderRoute: typeof DocsFinancialRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/education': {
      id: '/docs/education'
      path: '/education'
      fullPath: '/docs/education'
      preLoaderRoute: typeof DocsEducationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recover-password': {
      id: '/auth/recover-password'
      path: '/auth/recover-password'
      fullPath: '/auth/recover-password'
      preLoaderRoute: typeof AuthRecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/manage-news': {
      id: '/_layout/manage-news'
      path: '/manage-news'
      fullPath: '/manage-news'
      preLoaderRoute: typeof LayoutManageNewsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutManageNewsRoute: typeof LayoutManageNewsRoute
  LayoutUsersRoute: typeof LayoutUsersRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutManageNewsRoute: LayoutManageNewsRoute,
  LayoutUsersRoute: LayoutUsersRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface DocsRouteChildren {
  DocsEducationRoute: typeof DocsEducationRoute
  DocsFinancialRoute: typeof DocsFinancialRoute
  DocsLegalRoute: typeof DocsLegalRoute
  DocsOrganizationalRoute: typeof DocsOrganizationalRoute
  DocsRulesRoute: typeof DocsRulesRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsEducationRoute: DocsEducationRoute,
  DocsFinancialRoute: DocsFinancialRoute,
  DocsLegalRoute: DocsLegalRoute,
  DocsOrganizationalRoute: DocsOrganizationalRoute,
  DocsRulesRoute: DocsRulesRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactsRoute: ContactsRoute,
  DocsRoute: DocsRouteWithChildren,
  FederationRoute: FederationRoute,
  NewsRoute: NewsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoverPasswordRoute: AuthRecoverPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
